- name: Configuration of Backend services
  hosts: backend
  become: yes
  vars:
    login_host: db.somustack.online
    login_password: ExpenseApp@1
    login_user: root
  
  tasks:
  - name: Disbaling the NodeJS services
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enabling the NodeJS services 20JS
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Installing the updated NodeJS
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - nodejs
    - mysql